server:
  port: 8091

spring:
  kafka:
    # ??kafka server?????????????????
    bootstrap-servers:
      - 192.168.32.139:9092
      - 192.168.32.137:9092
      - 192.168.32.138:9092
    ###########??????????###########
    producer:
      # ????????????leader?????repli???????leader??????????????
      # ?retris?0??produce?????retirs?????repli??????leader????????????
      retries: 3
      # ???????????,produce??????????????
      # ????????????????? Producer ????????????????
      # ??????????????????????????????????????????16384???????16K?
      batch-size: 16384
      # produce???????????????buffer.memory?????
      # #Producer ??????????????????????33554432?????
      buffer-memory: 33554432
      #??????????????????????????????????none,snappy,gzip,lz4?snappy?????Google???
      #?????????????????????????gzip?????CPU?????????????????????????????????Kafka?????
      #????????????none???????????????
      compressionType: none
      #procedure??leader?????????????????????????????????????????
      #acks = 0 ????????????????????????????????????????????????????????
      #    ??????????????????????????????????????????????????????????-1?
      #acks = 1 ????leader?????????????????????????????????????????????leader??????
      #    ????????????????????????????????
      #acks = all ????leader?????????????????????????????????????????????????????????
      #    ????acks = -1????
      #????????all, -1, 0, 1
#      acks: all
      # ????key??????????
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      #      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      # ??????
      properties:
        request.timeout.ms: 30000
    ###########??????????###########
    consumer:
      properties:
        group.id: 0
        session.timeout.ms: 120000 # ????????(??????consumer??????,????rebalance??)
        request.timeout.ms: 180000 # ????????
      # ??????offset
      enable-auto-commit: true
      # ??offset??(??????????offset)
      auto:
        commit:
          interval:
            ms: 1000
      #??'enable.auto.commit'?true????????????Kafka????????????????5000?
      #spring.kafka.consumer.auto-commit-interval=100

      # ?kafka?????offset?offset??????????offset
      # earliest:?????????offset;
      # latest:?????????offset(???????????);
      # none:??????????????offset,?????;
      auto-offset-reset: latest

      # Kafka????????????
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # ???????????????
      max-poll-records: 50

    listener:
      missing-topics-fatal: false # ??????topic????????????(??)
      type: batch # ??????
      concurrency: 5 # ????????
      ack-mode: manual_immediate # ??????ack



#kafka topic??
kafka:
  topic:
    group-id: topicGroupId
    topic-name:
      - topic1
      - topic2
      - topic3